### ISSUE TITLE
tado Error: Cannot read properties of undefined (reading 'concentration')

### ISSUE THREAD

**Issue by Christian-CFP** [SeydX/homebridge-tado-platform#143]
tado Error: Cannot read properties of undefined (reading 'concentration') ?
Thats since 3 days. Don't know what causees this.

**Comment by adamstamper** [comment]
Yep same!
`TypeError: Cannot read properties of undefined (reading 'concentration')
    at updateAirQuality (/var/lib/homebridge/node_modules/homebridge-tado-platform/src/helper/handler.js:1274:53)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getStates (/var/lib/homebridge/node_modules/homebridge-tado-platform/src/helper/handler.js:625:9)`

**Comment by SaschaRH** [comment]
Me too. NodeJS v18.16.1. Maybe Tado changed the API?

**Comment by Christian-CFP** [comment]
I'm using Node 16.20.1

**Comment by hanwalt** [comment]
Same error for me, Node v18.6.1

**Comment by adavison007** [comment]
I'm having the same issue too... 

[21/07/2023, 19:49:57] [TadoPlatform] TypeError: Cannot read properties of undefined (reading 'concentration')
    at updateAirQuality (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:1274:53)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getStates (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:625:9)

**Comment by adavison007** [comment]
@seydx Are you aware of this issue?

**Comment by adavison007** [comment]
Has anyone found a way to resolve this issue?

**Comment by Christian-CFP** [comment]
Nope 👎  and @seydx does not care, I guess but I do not hope/wish so.

**Comment by SaschaRH** [comment]
hmmm...
https://community.tado.com/de/discussion/19373/warum-sind-in-der-app-die-pollenvorhersage-und-die-luftverschmutzungswerte-nicht-mehr-vorhanden

**Comment by Christian-CFP** [comment]
I guess a feature that they have dumped maybe? But what's the point regarding this issue?

**Comment by SaschaRH** [comment]
Well the error is: reading "concentration" at "updateAirQuality". So my guess is, the API changed and "concentration" (CO2, pollen, whatever) is empty.

**Comment by Christian-CFP** [comment]
Ok, now I got it! THX. Thats possible. If this only relates to the airquality and not the entire system. I mean the error...
Becaus I do not get the at ...
This is all I get :"TypeError: Cannot read properties of undefined (reading 'concentration')"
Im on HOOBS ;)

**Comment by SaschaRH** [comment]
I looks just like that. I checked /homebridge-tado-platform/tree/master/src/helper/handler.js and the error occurs at 
let pm10 = returnPol('PM<sub>10</sub>')[0].concentration.value; which refers to particulate matter (PM) and line 625 await updateAirQuality();.
I really hope this project is active maintained, since the last update was 2021... :(

**Comment by Christian-CFP** [comment]
I am afraid that this project is not actively supervised. Just like his other projects like the FRITZ Platform.

**Comment by adavison007** [comment]
@seydx Would a donation help you getting this challenge resolved? I love your plugin, it's the best for Tado, so some assistance in fixing this would be appreciated by many

**Comment by SaschaRH** [comment]
Just turned off "Air quality" and the error is gone:

"weather": {
                        "temperatureSensor": false,
                        "solarIntensity": false,
                        "accTypeSolarIntensity": "LIGHTBULB",
                        **"airQuality": false**
                    },

I'd sure like to have the air quality back, but that's more a Tado issue.

**Comment by Christian-CFP** [comment]
Yes, that's what I have done yesterday.

**Comment by hanwalt** [comment]
I think the problem is that Tado removed the items for "pollen forecast" and "air pollution values" from their App and therefore from their API
