### ISSUE TITLE
New Hot Water function crashes homebridge

### ISSUE THREAD

**Issue by mylesagray** [SeydX/homebridge-tado-platform#25]
```[5/6/2019, 10:27:58 AM] [Tado] [INFO] Configuring accessory Hot Water BU3344960000
[5/6/2019, 10:27:58 AM] TypeError: Cannot read property 'toString' of undefined
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:54:59)
    at boiler_Accessory.handleValve (/homebridge/node_modules/homebridge-tado-platform/src/accessories/boiler.js:58:22)
    at new boiler_Accessory (/homebridge/node_modules/homebridge-tado-platform/src/accessories/boiler.js:33:10)
    at TadoPlatform._addOrConfigure (/homebridge/node_modules/homebridge-tado-platform/src/platform.js:510:11)
    at TadoPlatform.configureAccessory (/homebridge/node_modules/homebridge-tado-platform/src/platform.js:629:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

This causes homebridge to SIG TERM on my install

**Comment by mylesagray** [comment]
Closing - was resolved by another reConfig: true and re-enabling all sensors.
