### ISSUE TITLE
Indicator only orange and blue...no green

### ISSUE THREAD

**Issue by T-Bone90** [SeydX/homebridge-tado-platform#58]
(sorry for my bad English)
What else I can think of. I either get a message indicating that it is being heated (orange) or that it is being cooled (blue). I don't get any green display.
Even when the temperature is reached, it says "is being cooled" ...
Is it wanted like that?

And is it possible to get a message if window open. That i can see in homekit when the window is opened.

**Comment by SeydX** [comment]
The green indicator if for the "auto" mode reserved.

**Comment by T-Bone90** [comment]
Oh ok thats bad.
Because look at the picture.
Red and Yellow same room. One with your plugin, one with Tado original HomeKit integration.

When the temperature in the room is reached, it does not have to display heating / cooling and should turn green.
For me, blue means that the heating is off because it is too warm in the room. But that's not true at all, so the Plugin shows wrong values in my opinion.
"Auto" means that he uses the time schedule.

**Comment by SeydX** [comment]
There is an open window option to enable a sensor in homekit, look at example config

https://github.com/SeydX/homebridge-tado-platform/blob/ac28ff456907e59c12bf20babc6533cc43012062/example-config.json#L81

**Comment by SeydX** [comment]
@T-Bone90 

Fixed in v6.0.9 (for HEATING devices "easyMode" must be enabled in config to show this state)

**Comment by T-Bone90** [comment]
@SeydX thank you but I get error and it doesn't work for me.

`TypeError: Cannot read property 'getCharacteristic' of undefined
    at /usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:1022:24
    at Array.forEach (<anonymous>)
    at updateZones (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:900:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at getStates (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:699:9)
[22.3.2021, 17:08:39] [TadoPlatform] TypeError: Cannot read property 'getCharacteristic' of undefined
    at /usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:1022:24
    at Array.forEach (<anonymous>)
    at updateZones (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:900:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at getStates (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:699:9)
TypeError: Cannot read property 'getCharacteristic' of undefined
    at /usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:1022:24
    at Array.forEach (<anonymous>)
    at updateZones (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:900:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at getStates (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:699:9)
[22.3.2021, 17:09:10] [TadoPlatform] TypeError: Cannot read property 'getCharacteristic' of undefined
    at /usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:1022:24
    at Array.forEach (<anonymous>)
    at updateZones (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:900:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at getStates (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:699:9)`

Red Rooms are the same (original Tado and your plugin) and purple rooms are the same.
The Thermostat in "Badezimmer" is 20°. Your plugin shows "AUS/OFF"
The same with "Wohnzimmer".
