### ISSUE TITLE
many new issues

### ISSUE THREAD

**Issue by T-Bone90** [SeydX/homebridge-tado-platform#71]
I got many issues with the last update.

> [26.3.2021, 06:51:00] [TadoPlatform] Mein Zuhause: {"statusCode":406,"error":"Not Acceptable","message":"The content-type is not JSON compatible"}

> [27.3.2021, 10:36:24] [TadoPlatform] Mein Zuhause: {"code":"EAI_AGAIN","message":"Cannot reach Tado. No response received."}
RequestError: getaddrinfo EAI_AGAIN my.tado.com
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-tado-platform/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/usr/local/lib/node_modules/homebridge-tado-platform/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  code: 'EAI_AGAIN',
  timings: {
    start: 1616837837653,
    socket: 1616837837653,
    lookup: 1616837847664,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1616837847665,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 10011,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 10012
    }
  }
}
[27.3.2021, 10:37:27] [TadoPlatform] Mein Zuhause: {"code":"EAI_AGAIN","message":"Cannot reach Tado. No response received."}

> [28.3.2021, 05:04:39] [Homebridge UI] Creating temporary backup archive at /tmp/homebridge-backup-6jdpZf/homebridge-backup-CC223DE3CE30.tar.gz
Error: The content-type is not JSON compatible
    at finish (/usr/local/lib/node_modules/homebridge-tado-platform/node_modules/@hapi/wreck/lib/index.js:383:42)
    at wrapped (/usr/local/lib/node_modules/homebridge-tado-platform/node_modules/@hapi/hoek/lib/once.js:17:13)
    at module.exports.internals.Recorder.onReaderFinish (/usr/local/lib/node_modules/homebridge-tado-platform/node_modules/@hapi/wreck/lib/index.js:436:20)
    at Object.onceWrapper (events.js:421:28)
    at module.exports.internals.Recorder.emit (events.js:327:22)
    at finish (_stream_writable.js:657:10)
    at finishMaybe (_stream_writable.js:644:9)
    at afterWrite (_stream_writable.js:473:3)
    at afterWriteTick (_stream_writable.js:453:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21) {
  data: {
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 504,
      statusMessage: 'Gateway Time-out',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [ClientRequest],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    }
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 406,
    payload: {
      statusCode: 406,
      error: 'Not Acceptable',
      message: 'The content-type is not JSON compatible'
    },
    headers: {}
  }
}
[28.3.2021, 09:47:35] [TadoPlatform] Mein Zuhause: {"statusCode":406,"error":"Not Acceptable","message":"The content-type is not JSON compatible"}

**Comment by SeydX** [comment]
@T-Bone90 

Does a downgrade fix the issue?

**Comment by T-Bone90** [comment]
I don't know. I haven't looked inside for several days and suddenly discovered these messages. I also cannot say what status this message appears in.

**Comment by SeydX** [comment]
> {"code":"EAI_AGAIN","message":"Cannot reach Tado. No response received."}

**Comment by T-Bone90** [comment]
?

**Comment by SeydX** [comment]
Tried a restart? Maybe just tado isnt just reachable

**Comment by T-Bone90** [comment]
Yes, I'll try that and just look back the days.

**Comment by T-Bone90** [comment]
Despite restarting today again ...

> [2.4.2021, 02:28:02] [Homebridge UI] Creating temporary backup archive at /tmp/homebridge-backup-nJg1rc/homebridge-backup-xxxxxxxx.tar.gz
RequestError: getaddrinfo EAI_AGAIN my.tado.com
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-tado-platform/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/usr/local/lib/node_modules/homebridge-tado-platform/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  code: 'EAI_AGAIN',
  timings: {
    start: 1617353896352,
    socket: 1617353896353,
    lookup: 1617353906364,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1617353906366,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 10011,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 10014
    }
  }
}
[2.4.2021, 10:58:26] [TadoPlatform] Mein Zuhause: {"code":"EAI_AGAIN","message":"Cannot reach Tado. No response received."}

**Comment by SeydX** [comment]
i couldnt reproduce this issue. Can u try v6.0.12 pls and give me some more information on how i could reproduce this?

And your config.json pls
