### ISSUE TITLE
Zuhause Presence Lock: Home: false not working

### ISSUE THREAD

**Issue by sebiweise** [SeydX/homebridge-tado-platform#76]
I want to use the Home/Away-Switch in HomeKit but the following error appears every time I use the Switch.

![image](https://user-images.githubusercontent.com/22999200/114395093-49c85000-9b9c-11eb-8cd5-2bd8b21dbd4d.png)

`HTTPError: Response code 422 (Unprocessable Entity)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-tado-platform/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: undefined,
  timings: {
    start: ******,
    socket: *****,
    lookup: *****,
    connect: *****,
    secureConnect: *****,
    upload: *****,
    response: *****,
    end: *****,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 1,
      tcp: 39,
      tls: 43,
      request: 0,
      firstByte: 5611,
      download: 2,
      total: 5697
    }
  }
}
[4/12/2021, 2:31:56 PM] [TadoPlatform] Zuhause: {}`

**Comment by sebiweise** [comment]
My fault, setting Presence Lock -> Home to false doesnt work, instead I have to set Presence Lock -> Away to True.
