### ISSUE TITLE
RequestError - While setting new state

### ISSUE THREAD

**Issue by MexxReal** [SeydX/homebridge-tado-platform#77]
If I want to change the state of my heaters automatically I get an error in the log as follows.

14.4.2021, 11:35:35 [TadoPlatform] BaMa Schlafzimmer Heater: State: 0
14.4.2021, 11:35:44 RequestError: getaddrinfo EAI_AGAIN my.tado.com
14.4.2021, 11:35:44 at ClientRequest.<anonymous> (/hoobs/node_modules/got/dist/source/core/index.js:956:111)
14.4.2021, 11:35:44 at Object.onceWrapper (events.js:422:26)
14.4.2021, 11:35:44 at ClientRequest.emit (events.js:327:22)
14.4.2021, 11:35:44 at ClientRequest.origin.emit (/hoobs/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
14.4.2021, 11:35:44 at TLSSocket.socketErrorListener (_http_client.js:469:9)
14.4.2021, 11:35:44 at TLSSocket.emit (events.js:315:20)
14.4.2021, 11:35:44 at emitErrorNT (internal/streams/destroy.js:106:8)
14.4.2021, 11:35:44 at emitErrorCloseNT (internal/streams/destroy.js:74:3)
14.4.2021, 11:35:44 at processTicksAndRejections (internal/process/task_queues.js:80:21)
14.4.2021, 11:35:44 at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
14.4.2021, 11:35:44 code: 'EAI_AGAIN',
14.4.2021, 11:35:44 timings: {
14.4.2021, 11:35:44 start: 1618392939237,
14.4.2021, 11:35:44 socket: 1618392939238,
14.4.2021, 11:35:44 lookup: 1618392944242,
14.4.2021, 11:35:44 connect: undefined,
14.4.2021, 11:35:44 secureConnect: undefined,
14.4.2021, 11:35:44 upload: undefined,
14.4.2021, 11:35:44 response: undefined,
14.4.2021, 11:35:44 end: undefined,
14.4.2021, 11:35:44 error: 1618392944242,
14.4.2021, 11:35:44 abort: undefined,
14.4.2021, 11:35:44 phases: {
14.4.2021, 11:35:44 wait: 1,
14.4.2021, 11:35:44 dns: 5004,
14.4.2021, 11:35:44 tcp: undefined,
14.4.2021, 11:35:44 tls: undefined,
14.4.2021, 11:35:44 request: undefined,
14.4.2021, 11:35:44 firstByte: undefined,
14.4.2021, 11:35:44 download: undefined,
14.4.2021, 11:35:44 total: 5005
14.4.2021, 11:35:44 }
14.4.2021, 11:35:44 }
14.4.2021, 11:35:44 }
14.4.2021, 11:35:44 [TadoPlatform] BaMa: {"code":"EAI_AGAIN","message":"Cannot reach Tado. No response received."}
14.4.2021, 11:35:53 RequestError: getaddrinfo EAI_AGAIN my.tado.com
14.4.2021, 11:35:53 at ClientRequest.<anonymous> (/hoobs/node_modules/got/dist/source/core/index.js:956:111)
14.4.2021, 11:35:53 at Object.onceWrapper (events.js:422:26)
14.4.2021, 11:35:53 at ClientRequest.emit (events.js:327:22)
14.4.2021, 11:35:53 at ClientRequest.origin.emit (/hoobs/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
14.4.2021, 11:35:53 at TLSSocket.socketErrorListener (_http_client.js:469:9)
14.4.2021, 11:35:53 at TLSSocket.emit (events.js:315:20)
14.4.2021, 11:35:53 at emitErrorNT (internal/streams/destroy.js:106:8)
14.4.2021, 11:35:53 at emitErrorCloseNT (internal/streams/destroy.js:74:3)
14.4.2021, 11:35:53 at processTicksAndRejections (internal/process/task_queues.js:80:21)
14.4.2021, 11:35:53 at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
14.4.2021, 11:35:53 code: 'EAI_AGAIN',
14.4.2021, 11:35:53 timings: {
14.4.2021, 11:35:53 start: 1618392948388,
14.4.2021, 11:35:53 socket: 1618392948389,
14.4.2021, 11:35:53 lookup: 1618392953392,
14.4.2021, 11:35:53 connect: undefined,
14.4.2021, 11:35:53 secureConnect: undefined,
14.4.2021, 11:35:53 upload: undefined,
14.4.2021, 11:35:53 response: undefined,
14.4.2021, 11:35:53 end: undefined,
14.4.2021, 11:35:53 error: 1618392953393,
14.4.2021, 11:35:53 abort: undefined,
14.4.2021, 11:35:53 phases: {
14.4.2021, 11:35:53 wait: 1,
14.4.2021, 11:35:53 dns: 5003,
14.4.2021, 11:35:53 tcp: undefined,
14.4.2021, 11:35:53 tls: undefined,
14.4.2021, 11:35:53 request: undefined,
14.4.2021, 11:35:53 firstByte: undefined,
14.4.2021, 11:35:53 download: undefined,
14.4.2021, 11:35:53 total: 5005
14.4.2021, 11:35:53 }
14.4.2021, 11:35:53 }
14.4.2021, 11:35:53 }
14.4.2021, 11:35:53 [TadoPlatform] BaMa: {"code":"EAI_AGAIN","message":"Cannot reach Tado. No response received."}

Due to this error all my automations are not working anymore. 
Updating the pi and restarting it and the tado-bridge too, doesn't show any effects. 

I'm using hoobs as/ in docker, but it worked fine until the error occured. 

How to fix this issue?

**Comment by MexxReal** [comment]
I actually saw some new log-entries:

14.4.2021, 12:09:52 Error: getaddrinfo EAI_AGAIN auth.tado.com
14.4.2021, 12:09:52 at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
14.4.2021, 12:09:52 errno: -3001,
14.4.2021, 12:09:52 code: 'EAI_AGAIN',
14.4.2021, 12:09:52 syscall: 'getaddrinfo',
14.4.2021, 12:09:52 hostname: 'auth.tado.com',
14.4.2021, 12:09:52 trace: [ { method: 'POST', url: 'https://auth.tado.com/oauth/token' } ],
14.4.2021, 12:09:52 isBoom: true,
14.4.2021, 12:09:52 isServer: true,
14.4.2021, 12:09:52 data: null,
14.4.2021, 12:09:52 output: {
14.4.2021, 12:09:52 statusCode: 502,
14.4.2021, 12:09:52 payload: {
14.4.2021, 12:09:52 message: 'Client request error: getaddrinfo EAI_AGAIN auth.tado.com',
14.4.2021, 12:09:52 statusCode: 502,
14.4.2021, 12:09:52 error: 'Bad Gateway'
14.4.2021, 12:09:52 },
14.4.2021, 12:09:52 headers: {}
14.4.2021, 12:09:52 }
14.4.2021, 12:09:52 }
14.4.2021, 12:09:52 [TadoPlatform] BaMa: {"message":"Client request error: getaddrinfo EAI_AGAIN auth.tado.com","statusCode":502,"error":"Bad Gateway"}

**Comment by MexxReal** [comment]
After Updating and rebooting my Fritzbox (6591, V7.26) everything worked as defined until now. 
After checking why my automation doesn't set the right state to the thermostats I saw the following log entries.

26.4.2021, 06:48:55 Error: The content-type is not JSON compatible
26.4.2021, 06:48:55 at finish (/hoobs/node_modules/@hapi/wreck/lib/index.js:383:42)
26.4.2021, 06:48:55 at wrapped (/hoobs/node_modules/@hapi/hoek/lib/once.js:17:13)
26.4.2021, 06:48:55 at module.exports.internals.Recorder.onReaderFinish (/hoobs/node_modules/@hapi/wreck/lib/index.js:436:20)
26.4.2021, 06:48:55 at Object.onceWrapper (events.js:421:28)
26.4.2021, 06:48:55 at module.exports.internals.Recorder.emit (events.js:327:22)
26.4.2021, 06:48:55 at finish (internal/streams/writable.js:657:10)
26.4.2021, 06:48:55 at finishMaybe (internal/streams/writable.js:644:9)
26.4.2021, 06:48:55 at afterWrite (internal/streams/writable.js:473:3)
26.4.2021, 06:48:55 at afterWriteTick (internal/streams/writable.js:453:10)
26.4.2021, 06:48:55 at processTicksAndRejections (internal/process/task_queues.js:79:21) {
26.4.2021, 06:48:55 data: {
26.4.2021, 06:48:55 res: IncomingMessage {
26.4.2021, 06:48:55 _readableState: [ReadableState],
26.4.2021, 06:48:55 _events: [Object: null prototype],
26.4.2021, 06:48:55 _eventsCount: 2,
26.4.2021, 06:48:55 _maxListeners: undefined,
26.4.2021, 06:48:55 socket: [TLSSocket],
26.4.2021, 06:48:55 httpVersionMajor: 1,
26.4.2021, 06:48:55 httpVersionMinor: 1,
26.4.2021, 06:48:55 httpVersion: '1.1',
26.4.2021, 06:48:55 complete: true,
26.4.2021, 06:48:55 headers: [Object],
26.4.2021, 06:48:55 rawHeaders: [Array],
26.4.2021, 06:48:55 trailers: {},
26.4.2021, 06:48:55 rawTrailers: [],
26.4.2021, 06:48:55 aborted: false,
26.4.2021, 06:48:55 upgrade: false,
26.4.2021, 06:48:55 url: '',
26.4.2021, 06:48:55 method: null,
26.4.2021, 06:48:55 statusCode: 504,
26.4.2021, 06:48:55 statusMessage: 'Gateway Time-out',
26.4.2021, 06:48:55 client: [TLSSocket],
26.4.2021, 06:48:55 _consuming: false,
26.4.2021, 06:48:55 _dumped: false,
26.4.2021, 06:48:55 req: [ClientRequest],
26.4.2021, 06:48:55 [Symbol(kCapture)]: false,
26.4.2021, 06:48:55 [Symbol(RequestTimeout)]: undefined
26.4.2021, 06:48:55 }
26.4.2021, 06:48:55 },
26.4.2021, 06:48:55 isBoom: true,
26.4.2021, 06:48:55 isServer: false,
26.4.2021, 06:48:55 output: {
26.4.2021, 06:48:55 statusCode: 406,
26.4.2021, 06:48:55 payload: {
26.4.2021, 06:48:55 statusCode: 406,
26.4.2021, 06:48:55 error: 'Not Acceptable',
26.4.2021, 06:48:55 message: 'The content-type is not JSON compatible'
26.4.2021, 06:48:55 },
26.4.2021, 06:48:55 headers: {}
26.4.2021, 06:48:55 }
26.4.2021, 06:48:55 }
26.4.2021, 06:48:55 [TadoPlatform] BaMa: {"statusCode":406,"error":"Not Acceptable","message":"The content-type is not JSON compatible"}

After reboot of Fritzbox:

26.4.2021, 07:13:24 Bridge is running on port 51826.
26.4.2021, 07:14:15 RequestError: getaddrinfo EAI_AGAIN my.tado.com
26.4.2021, 07:14:15 at ClientRequest.<anonymous> (/hoobs/node_modules/got/dist/source/core/index.js:956:111)
26.4.2021, 07:14:15 at Object.onceWrapper (events.js:422:26)
26.4.2021, 07:14:15 at ClientRequest.emit (events.js:327:22)
26.4.2021, 07:14:15 at ClientRequest.origin.emit (/hoobs/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
26.4.2021, 07:14:15 at TLSSocket.socketErrorListener (_http_client.js:469:9)
26.4.2021, 07:14:15 at TLSSocket.emit (events.js:315:20)
26.4.2021, 07:14:15 at emitErrorNT (internal/streams/destroy.js:106:8)
26.4.2021, 07:14:15 at emitErrorCloseNT (internal/streams/destroy.js:74:3)
26.4.2021, 07:14:15 at processTicksAndRejections (internal/process/task_queues.js:80:21)
26.4.2021, 07:14:15 at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
26.4.2021, 07:14:15 code: 'EAI_AGAIN',
26.4.2021, 07:14:15 timings: {
26.4.2021, 07:14:15 start: 1619414050016,
26.4.2021, 07:14:15 socket: 1619414050017,
26.4.2021, 07:14:15 lookup: 1619414055022,
26.4.2021, 07:14:15 connect: undefined,
26.4.2021, 07:14:15 secureConnect: undefined,
26.4.2021, 07:14:15 upload: undefined,
26.4.2021, 07:14:15 response: undefined,
26.4.2021, 07:14:15 end: undefined,
26.4.2021, 07:14:15 error: 1619414055023,
26.4.2021, 07:14:15 abort: undefined,
26.4.2021, 07:14:15 phases: {
26.4.2021, 07:14:15 wait: 1,
26.4.2021, 07:14:15 dns: 5005,
26.4.2021, 07:14:15 tcp: undefined,
26.4.2021, 07:14:15 tls: undefined,
26.4.2021, 07:14:15 request: undefined,
26.4.2021, 07:14:15 firstByte: undefined,
26.4.2021, 07:14:15 download: undefined,
26.4.2021, 07:14:15 total: 5007
26.4.2021, 07:14:15 }
26.4.2021, 07:14:15 }
26.4.2021, 07:14:15 }
26.4.2021, 07:14:15 [TadoPlatform] BaMa: {"code":"EAI_AGAIN","message":"Cannot reach Tado. No response received."}

26.4.2021, 07:15:35 RequestError: self signed certificate
26.4.2021, 07:15:35 at ClientRequest.<anonymous> (/hoobs/node_modules/got/dist/source/core/index.js:956:111)
26.4.2021, 07:15:35 at Object.onceWrapper (events.js:422:26)
26.4.2021, 07:15:35 at ClientRequest.emit (events.js:327:22)
26.4.2021, 07:15:35 at ClientRequest.origin.emit (/hoobs/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
26.4.2021, 07:15:35 at TLSSocket.socketErrorListener (_http_client.js:469:9)
26.4.2021, 07:15:35 at TLSSocket.emit (events.js:315:20)
26.4.2021, 07:15:35 at emitErrorNT (internal/streams/destroy.js:106:8)
26.4.2021, 07:15:35 at emitErrorCloseNT (internal/streams/destroy.js:74:3)
26.4.2021, 07:15:35 at processTicksAndRejections (internal/process/task_queues.js:80:21)
26.4.2021, 07:15:35 at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
26.4.2021, 07:15:35 at TLSSocket.emit (events.js:315:20)
26.4.2021, 07:15:35 at TLSSocket._finishInit (_tls_wrap.js:932:8)
26.4.2021, 07:15:35 at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
26.4.2021, 07:15:35 code: 'DEPTH_ZERO_SELF_SIGNED_CERT',
26.4.2021, 07:15:35 timings: {
26.4.2021, 07:15:35 start: 1619414133200,
26.4.2021, 07:15:35 socket: 1619414133201,
26.4.2021, 07:15:35 lookup: 1619414135708,
26.4.2021, 07:15:35 connect: 1619414135712,
26.4.2021, 07:15:35 secureConnect: undefined,
26.4.2021, 07:15:35 upload: undefined,
26.4.2021, 07:15:35 response: undefined,
26.4.2021, 07:15:35 end: undefined,
26.4.2021, 07:15:35 error: 1619414135793,
26.4.2021, 07:15:35 abort: undefined,
26.4.2021, 07:15:35 phases: {
26.4.2021, 07:15:35 wait: 1,
26.4.2021, 07:15:35 dns: 2507,
26.4.2021, 07:15:35 tcp: 4,
26.4.2021, 07:15:35 tls: undefined,
26.4.2021, 07:15:35 request: undefined,
26.4.2021, 07:15:35 firstByte: undefined,
26.4.2021, 07:15:35 download: undefined,
26.4.2021, 07:15:35 total: 2593
26.4.2021, 07:15:35 }
26.4.2021, 07:15:35 }
26.4.2021, 07:15:35 }
26.4.2021, 07:15:35 [TadoPlatform] BaMa: {"code":"DEPTH_ZERO_SELF_SIGNED_CERT","message":"Cannot reach Tado. No response received."}

**Comment by MexxReal** [comment]
Sry for the delay. I updated everything on pi, including npm. Actually there are no more error entries in log file. 
I will have an eye on the log, but for now everything works as defined :)
