### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Nils89** [SeydX/homebridge-tado-platform#84]
Hi got this error message:

[7/9/2021, 8:23:51 AM] [TadoPlatform] TypeError: Cannot read property 'celsius' of undefined
    at updateZones (/usr/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:884:49)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.getStates (/usr/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:607:32)

Happens after add a AC to Tado

**Comment by Nils89** [comment]
Error is gone if I deactivate the AC Zone in settings
