### ISSUE TITLE
TypeError: Cannot read property

### ISSUE THREAD

**Issue by pespinel** [SeydX/homebridge-tado-platform#90]
Hi, I am getting this error after the initial setup.

```
[06/09/2021, 08:01:24] [TadoPlatform] Casa: Checking access token..
[06/09/2021, 08:01:24] [TadoPlatform] Casa: Access token NOT expired
[06/09/2021, 08:01:24] [TadoPlatform] Casa: Using https://my.tado.com
[06/09/2021, 08:01:24] [TadoPlatform] Casa: API request GET /api/v2/homes/735087/zones/1/state <pending>
[06/09/2021, 08:01:29] [TadoPlatform] Casa: API request GET /api/v2/homes/735087/zones/1/state <success>
[06/09/2021, 08:01:29] [TadoPlatform] Casa: API request GET /api/v2/homes/735087/zones/1/state <response> {"tadoMode":"AWAY","geolocationOverride":false,"geolocationOverrideDisableTime":null,"preparation":null,"setting":{"type":"AIR_CONDITIONING","power":"OFF"},"overlayType":"MANUAL","overlay":{"type":"MANUAL","setting":{"type":"AIR_CONDITIONING","power":"OFF"},"termination":{"type":"MANUAL","typeSkillBasedApp":"MANUAL","projectedExpiry":null}},"openWindow":null,"nextScheduleChange":null,"nextTimeBlock":null,"link":{"state":"ONLINE"},"activityDataPoints":{"acPower":{"timestamp":"2021-09-03T08:09:27.468Z","type":"POWER","value":"OFF"}},"sensorDataPoints":{"insideTemperature":{"celsius":25.45,"fahrenheit":77.81,"timestamp":"2021-09-06T05:42:53.766Z","type":"TEMPERATURE","precision":{"celsius":0.1,"fahrenheit":0.1}},"humidity":{"type":"PERCENTAGE","percentage":46.3,"timestamp":"2021-09-06T05:42:53.766Z"}}}
[06/09/2021, 08:01:29] [TadoPlatform] TypeError: Cannot read property 'celsius' of undefined
    at updateZones (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:884:49)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at getStates (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:607:32)
```

The config was created by the UI configuration wizard:

```
{
            "name": "TadoPlatform",
            "debug": true,
            "homes": [
                {
                    "id": xxx,
                    "name": "Casa",
                    "username": "xxx",
                    "password": "yyy",
                    "polling": 30,
                    "temperatureUnit": "CELSIUS",
                    "geolocation": {
                        "longitude": "-x",
                        "latitude": "y"
                    },
                    "presence": {
                        "anyone": false,
                        "accTypeAnyone": "OCCUPANCY",
                        "user": [
                            {
                                "active": false,
                                "name": "iPhone",
                                "accType": "OCCUPANCY"
                            }
                        ]
                    },
                    "weather": {
                        "temperatureSensor": true,
                        "solarIntensity": true,
                        "accTypeSolarIntensity": "SENSOR",
                        "airQuality": true
                    },
                    "extras": {
                        "centralSwitch": false,
                        "runningInformation": false,
                        "presenceLock": false,
                        "accTypePresenceLock": "ALARM",
                        "boostSwitch": false,
                        "sheduleSwitch": false,
                        "turnoffSwitch": false
                    },
                    "zones": [
                        {
                            "active": true,
                            "id": 1,
                            "name": "Salón",
                            "delaySwitch": false,
                            "autoOffDelay": false,
                            "openWindowSensor": false,
                            "openWindowSwitch": false,
                            "airQuality": true,
                            "separateTemperature": false,
                            "separateHumidity": false,
                            "minStep": "1",
                            "minValue": 18,
                            "maxValue": 28,
                            "mode": "MANUAL",
                            "modeTimer": 30,
                            "easyMode": false,
                            "noBattery": false,
                            "type": "HEATING",
                            "boilerTempSupport": false,
                            "accTypeBoiler": "SWITCH"
                        }
                    ],
                    "telegram": {
                        "active": false
                    }
                }
            ],
            "platform": "TadoPlatform"
        }
```

**Comment by AlexH007** [comment]
I have something similar with the weather "concentration" .

My log :
BridgeTadoPlatformFEHLERTypeError: Cannot read properties of undefined (reading 'concentration')

Is there any news on that ?

Thanks

**Comment by CSchmidtDD** [comment]
I had the same problem after enabling the weather > air quality setting via configuration-file to true.

Following error ocurred:
`[11/6/2023, 11:59:47 AM] [Tado] TypeError: Cannot read properties of undefined (reading 'concentration')
    at updateAirQuality (/homebridge/node_modules/homebridge-tado-platform/src/helper/handler.js:1274:53)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getStates (/homebridge/node_modules/homebridge-tado-platform/src/helper/handler.js:625:9)`

I do have three Tado Heating devices setup correctly in different zones and entered the geolocation into the config.

**Comment by MarcZ2202** [comment]
Nothing new here?

I have the same problem as @pespinel
