### ISSUE TITLE
Problem with AC control

### ISSUE THREAD

**Issue by Plexitar** [SeydX/homebridge-tado-platform#95]
Hi!
thank you for the great work!

I have problem with TADO AC Control v.3 - in tado app i see from AC humidity and temprerature. Via tado platform I cannot control the AC and none of the sensor work. 

From debug:
[10/26/2021, 10:10:51 AM] [TadoPlatform] Lobzo: API request GET /api/v2/homes/448876/zones/5/state <pending>
[10/26/2021, 10:10:51 AM] [TadoPlatform] Lobzo: API request GET /api/v2/homes/448876/zones/5/state <success>
[10/26/2021, 10:10:51 AM] [TadoPlatform] Lobzo: API request GET /api/v2/homes/448876/zones/5/state <response> {"tadoMode":"HOME","geolocationOverride":false,"geolocationOverrideDisableTime":null,"preparation":null,"setting":{"type":"AIR_CONDITIONING","power":"OFF"},"overlayType":null,"overlay":null,"openWindow":null,"nextScheduleChange":{"start":"2021-10-26T20:00:00Z","setting":{"type":"AIR_CONDITIONING","power":"ON","mode":"DRY","fanLevel":"SILENT","verticalSwing":"ON","horizontalSwing":"ON"}},"nextTimeBlock":{"start":"2021-10-26T20:00:00.000Z"},"link":{"state":"ONLINE"},"activityDataPoints":{"acPower":{"timestamp":"2021-10-08T17:38:39.428Z","type":"POWER","value":"OFF"}},"sensorDataPoints":{"insideTemperature":{"celsius":19.95,"fahrenheit":67.91,"timestamp":"2021-10-26T10:03:48.593Z","type":"TEMPERATURE","precision":{"celsius":0.1,"fahrenheit":0.1}},"humidity":{"type":"PERCENTAGE","percentage":56,"timestamp":"2021-10-26T10:03:48.593Z"}}}
[10/26/2021, 10:10:51 AM] [TadoPlatform] TypeError: Cannot read property 'celsius' of undefined
    at updateZones (/homebridge/node_modules/homebridge-tado-platform/src/helper/handler.js:884:49)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at getStates (/homebridge/node_modules/homebridge-tado-platform/src/helper/handler.js:607:32)

**Comment by ArtemKiyashko** [comment]
Confirm AC control not supported at the moment. Is there a chance to get it working someday?

**Comment by dima-bzz** [comment]
Are there plans to add AC support? The [plugin](https://github.com/nitaybz/homebridge-tado-ac) that worked with AC is apparently no longer supported.

**Comment by MacForAll** [comment]
+1
Any plans on tado AC support?
