### ISSUE TITLE
Cannot read property 'celsius'

### ISSUE THREAD

**Issue by Stetocasa** [SeydX/homebridge-tado-platform#97]
Simple setting by plugin wizard, but in the LOG shows:

[TadoPlatform] TypeError: Cannot read property 'celsius' of undefined
    at updateZones (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:884:49)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at getStates (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:607:32)

**Comment by ghost** [comment]
I have the same problem. Have you found a solution for that?

**Comment by n0n4m3d** [comment]
I have the Same Probleme too
